# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50)),
                ("sku", models.CharField(blank=True, max_length=50)),
                ("codigo_barras", models.CharField(blank=True, max_length=50)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("producto", "Producto"),
                            ("servicio", "Servicio"),
                            ("combo", "Combo"),
                        ],
                        default="producto",
                        max_length=20,
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_compra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_mayoreo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("maneja_inventario", models.BooleanField(default=True)),
                (
                    "stock_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stock_maximo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("tiene_variantes", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("imagen_url", models.CharField(blank=True, max_length=500)),
                ("notas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="catalogs.categoria",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="core.empresa",
                    ),
                ),
                (
                    "impuesto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="catalogs.impuesto",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="productos",
                        to="catalogs.unidadmedida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "inventory_productos",
            },
        ),
        migrations.CreateModel(
            name="VarianteProducto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("sku", models.CharField(blank=True, max_length=50)),
                ("codigo_barras", models.CharField(blank=True, max_length=50)),
                ("atributos", models.JSONField(blank=True, default=dict)),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "precio_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="inventory.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante de Producto",
                "verbose_name_plural": "Variantes de Producto",
                "db_table": "inventory_variantes",
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("folio", models.CharField(max_length=50, unique=True)),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("ajuste", "Ajuste"),
                            ("traspaso_salida", "Traspaso Salida"),
                            ("traspaso_entrada", "Traspaso Entrada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "costo_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stock_antes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stock_despues",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("referencia_id", models.CharField(blank=True, max_length=100)),
                (
                    "tipo_referencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compra", "Compra"),
                            ("venta", "Venta"),
                            ("ajuste", "Ajuste Manual"),
                            ("traspaso", "Traspaso"),
                            ("devolucion", "Devolución"),
                            ("cancelacion_venta", "Cancelación de Venta"),
                            ("inicial", "Carga Inicial"),
                        ],
                        max_length=30,
                    ),
                ),
                ("motivo", models.CharField(blank=True, max_length=255)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_inventario",
                        to="core.empresa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventory.producto",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_inventario",
                        to="core.sucursal",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventory.varianteproducto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "db_table": "inventory_movimientos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stock_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stock_reservado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "costo_promedio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("ubicacion", models.CharField(blank=True, max_length=50)),
                ("pasillo", models.CharField(blank=True, max_length=20)),
                ("estante", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="core.empresa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="inventory.producto",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="core.sucursal",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="inventory.varianteproducto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventario",
                "db_table": "inventory_inventario",
            },
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["empresa", "activo"], name="inventory_p_empresa_b727b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["empresa", "nombre"], name="inventory_p_empresa_65c32e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(
                fields=["empresa", "producto"], name="inventory_m_empresa_0e843e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(
                fields=["empresa", "tipo_movimiento"],
                name="inventory_m_empresa_4c40c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(fields=["folio"], name="inventory_m_folio_89aad4_idx"),
        ),
        migrations.AddIndex(
            model_name="inventario",
            index=models.Index(
                fields=["empresa", "producto"], name="inventory_i_empresa_17b466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventario",
            index=models.Index(
                fields=["empresa", "sucursal"], name="inventory_i_empresa_3e1b14_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventario",
            unique_together={("producto", "variante", "sucursal")},
        ),
    ]
