# Generated by Django 4.2.9 on 2026-03-21 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_producto_visibilidad_publica'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producto',
            new_name='inventory_p_empresa_9346fb_idx',
            old_name='inv_prod_empresa_visib_idx',
        ),
    ]
