# Generated by Django 4.2.9 on 2026-03-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0003_cliente_y_pedidos"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movimientoinventario",
            name="inventory_m_folio_89aad4_idx",
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="folio",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="movimientoinventario",
            unique_together={("empresa", "folio")},
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(
                fields=["empresa", "folio"], name="inventory_m_empresa_b0e654_idx"
            ),
        ),
    ]
