# Generated by Django 4.2.9 on 2026-09-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_producto_imagen_origen_sugerenciaimagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="visibilidad_publica",
            field=models.CharField(
                choices=[
                    ("privado", "Privado"),
                    ("publico_sin_stock", "Público sin stock"),
                    ("publico_con_stock", "Público con stock"),
                ],
                db_index=True,
                default="publico_con_stock",
                max_length=20,
            ),
        ),
    ]
