# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_empleado", models.CharField(blank=True, max_length=20)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(max_length=100)),
                ("apellido_materno", models.CharField(blank=True, max_length=100)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("curp", models.CharField(blank=True, max_length=18)),
                ("rfc", models.CharField(blank=True, max_length=13)),
                ("nss", models.CharField(blank=True, max_length=11)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("puesto", models.CharField(max_length=100)),
                ("departamento", models.CharField(blank=True, max_length=100)),
                ("fecha_ingreso", models.DateField()),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("planta", "Planta"),
                            ("temporal", "Temporal"),
                            ("honorarios", "Honorarios"),
                            ("practicante", "Practicante"),
                        ],
                        default="planta",
                        max_length=20,
                    ),
                ),
                (
                    "salario_diario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("baja", "Baja"),
                            ("vacaciones", "Vacaciones"),
                            ("incapacidad", "Incapacidad"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaboradores",
                        to="core.empresa",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colaboradores",
                        to="core.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
                "db_table": "Colaboradores",
                "ordering": ["apellido_paterno", "nombre"],
                "unique_together": {("empresa", "numero_empleado")},
            },
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_registro", models.DateTimeField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("entrada_descanso", "Entrada a descanso"),
                            ("salida_descanso", "Salida de descanso"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("puntual", "Puntual"),
                            ("retardo", "Retardo"),
                            ("falta", "Falta"),
                            ("justificado", "Justificado"),
                        ],
                        default="puntual",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("registrado_por", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="hr.colaborador",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "db_table": "Asistencias",
                "ordering": ["-fecha", "-hora_registro"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "fecha"],
                        name="Asistencias_empresa_93d991_idx",
                    ),
                    models.Index(
                        fields=["colaborador", "fecha"],
                        name="Asistencias_colabor_579305_idx",
                    ),
                ],
            },
        ),
    ]
