# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("terceros", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                ("id_compra", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("folio", models.CharField(max_length=50, unique=True)),
                ("fecha_compra", models.DateField(auto_now_add=True)),
                ("fecha_entrega", models.DateField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("activo", "Activo"),
                            ("recibida_parcial", "Recibida Parcial"),
                            ("recibida", "Recibida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta_debito", "Tarjeta de Débito"),
                            ("tarjeta_credito", "Tarjeta de Crédito"),
                            ("transferencia", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "numero_factura",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "orden_compra",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras",
                        to="core.empresa",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="terceros.proveedor",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="core.sucursal",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compras",
                "ordering": ["-fecha_compra", "-id_compra"],
            },
        ),
        migrations.CreateModel(
            name="DetalleCompra",
            fields=[
                ("id_detalle", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "cantidad_recibida",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "impuesto_tasa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "impuesto_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="purchases.compra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_compra",
                        to="inventory.producto",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_compra",
                        to="inventory.varianteproducto",
                    ),
                ),
            ],
            options={
                "db_table": "detalle_compras",
                "ordering": ["id_detalle"],
            },
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(
                fields=["empresa", "fecha_compra"], name="compras_empresa_49bd03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(fields=["proveedor"], name="compras_proveed_c6e737_idx"),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(fields=["estado"], name="compras_estado_9eba4f_idx"),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(fields=["folio"], name="compras_folio_d60eed_idx"),
        ),
    ]
