# Generated by Django 4.2.9 on 2026-06-19 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("terceros", "0002_cliente_sat_fields"),
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="comprobante",
            field=models.FileField(
                blank=True, null=True, upload_to="compras/comprobantes/"
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras",
                to="terceros.proveedor",
            ),
        ),
    ]
