# Generated by Django 4.2.9 on 2026-06-19 21:19

import apps.purchases.models.compra
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0002_compra_comprobante_alter_compra_proveedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="comprobante",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.purchases.models.compra.comprobante_upload_to,
            ),
        ),
    ]
