# Generated by Django 4.2.9 on 2026-06-19 22:01

import apps.purchases.models.comprobante_compra
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchases", "0003_alter_compra_comprobante"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompraComprobante",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "archivo",
                    models.FileField(
                        upload_to=apps.purchases.models.comprobante_compra.comprobante_upload_to
                    ),
                ),
                (
                    "nombre_original",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprobantes",
                        to="purchases.compra",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comprobantes_compra_subidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compras_comprobantes",
                "ordering": ["created_at"],
            },
        ),
    ]
