# Generated by Django 4.2.9 on 2026-06-19 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0005_migrar_comprobante_unico"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="comprobante",
        ),
    ]
