# Generated by Django 4.2.9 on 2026-03-21 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('tezca_insignia', 'Insignia TEZCA'), ('admin_mensaje', 'Mensaje de Admin'), ('sistema', 'Sistema')], db_index=True, default='sistema', max_length=30)),
                ('titulo', models.CharField(max_length=160)),
                ('mensaje', models.TextField()),
                ('icono', models.CharField(default='bell', max_length=60)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.empresa')),
                ('remitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinatario', 'leida'], name='notificacio_destina_596317_idx'), models.Index(fields=['empresa', 'tipo'], name='notificacio_empresa_d0c74c_idx')],
            },
        ),
    ]
