# Generated by Django 4.2.9 on 2026-03-21 23:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0003_cliente_y_pedidos'),
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteStorefront',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_storefront', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Cliente Storefront',
                'verbose_name_plural': 'Clientes Storefront',
                'db_table': 'storefront_clientes',
                'unique_together': {('empresa', 'email')},
            },
        ),
        migrations.CreateModel(
            name='PedidoStorefront',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('apartado', 'Apartado (pago en tienda)'), ('pagado', 'Pagado con tarjeta'), ('en_proceso', 'En proceso'), ('listo', 'Listo para recoger'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo_en_tienda', 'Efectivo en tienda'), ('tarjeta', 'Tarjeta (Stripe)')], max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas_cliente', models.TextField(blank=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('stripe_client_secret', models.CharField(blank=True, max_length=200)),
                ('ticket_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='storefront.clientestorefront')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_storefront', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Pedido Storefront',
                'verbose_name_plural': 'Pedidos Storefront',
                'db_table': 'storefront_pedidos',
                'ordering': ['-created_at'],
                'unique_together': {('empresa', 'numero_pedido')},
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_snapshot', models.CharField(max_length=200)),
                ('precio_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='storefront.pedidostorefront')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='inventory.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'storefront_detalle_pedidos',
            },
        ),
    ]
