# Generated by Django 4.2.9 on 2026-04-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storefront", "0006_cliente_acepto_privacidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientestorefront",
            name="calle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="codigo_postal",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="colonia",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="estado",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="numero_exterior",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="numero_interior",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="pais",
            field=models.CharField(blank=True, default="México", max_length=100),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="razon_social",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="regimen_fiscal",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="rfc",
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name="clientestorefront",
            name="tipo_persona",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
