# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id_empresa",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("nombre_comercial", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("rfc", models.CharField(blank=True, max_length=13)),
                ("razon_social", models.CharField(blank=True, max_length=255)),
                ("regimen_fiscal", models.CharField(blank=True, max_length=100)),
                (
                    "tipo_negocio",
                    models.CharField(
                        choices=[
                            ("informal", "Informal"),
                            ("formal_simplificado", "Formal Simplificado"),
                            ("formal_completo", "Formal Completo"),
                        ],
                        default="informal",
                        max_length=30,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("profesional", "Profesional"),
                            ("empresarial", "Empresarial"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basico",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("direccion", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="empresas/logos/"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "core_empresa",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id_config",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("moneda", models.CharField(default="MXN", max_length=10)),
                ("decimales", models.PositiveSmallIntegerField(default=2)),
                ("genera_cfdi", models.BooleanField(default=False)),
                ("serie_factura", models.CharField(default="A", max_length=10)),
                ("folio_actual", models.PositiveIntegerField(default=1)),
                ("maneja_inventario", models.BooleanField(default=True)),
                ("alerta_stock_minimo", models.BooleanField(default=True)),
                ("email_notificaciones", models.EmailField(blank=True, max_length=254)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración",
                "verbose_name_plural": "Configuraciones",
                "db_table": "core_configuracion",
            },
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id_sucursal",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=20)),
                ("direccion", models.TextField(blank=True)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=100)),
                ("cp", models.CharField(blank=True, max_length=10)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("es_principal", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "db_table": "core_sucursal",
                "ordering": ["empresa", "nombre"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
    ]
