# Generated by Django 4.2.9 on 2026-04-02 22:55

import apps.core.models.empresa
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.models.empresa._empresa_logo_path,
            ),
        ),
    ]
