# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(blank=True, max_length=100)),
                ("apellido_materno", models.CharField(blank=True, max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("foto_url", models.URLField(blank=True, max_length=500)),
                ("activo", models.BooleanField(default=True)),
                ("verificado", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                ("intentos_fallidos", models.PositiveSmallIntegerField(default=0)),
                ("bloqueado_hasta", models.DateTimeField(blank=True, null=True)),
                ("idioma", models.CharField(default="es-mx", max_length=5)),
                (
                    "zona_horaria",
                    models.CharField(default="America/Mexico_City", max_length=50),
                ),
                ("tema", models.CharField(default="light", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="core.empresa",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "auth_usuarios",
            },
        ),
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("inventario", "Inventario"),
                            ("ventas", "Ventas"),
                            ("compras", "Compras"),
                            ("finanzas", "Finanzas"),
                            ("rrhh", "Recursos Humanos"),
                            ("auditoria", "Auditoría"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("ver", "Ver"),
                            ("crear", "Crear"),
                            ("editar", "Editar"),
                            ("eliminar", "Eliminar"),
                            ("exportar", "Exportar"),
                            ("admin", "Administrar"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "db_table": "auth_permisos",
                "unique_together": {("modulo", "accion")},
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True)),
                ("es_sistema", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "auth_roles",
                "unique_together": {("empresa", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_roles",
                        to="auth_module.rol",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si es None, el rol aplica a toda la empresa",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_roles",
                        to="core.sucursal",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario-Rol",
                "verbose_name_plural": "Usuarios-Roles",
                "db_table": "auth_usuario_roles",
                "unique_together": {("usuario", "rol", "sucursal")},
            },
        ),
        migrations.CreateModel(
            name="RolPermiso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rol_permisos",
                        to="auth_module.permiso",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rol_permisos",
                        to="auth_module.rol",
                    ),
                ),
            ],
            options={
                "db_table": "auth_rol_permisos",
                "unique_together": {("rol", "permiso")},
            },
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["empresa", "activo"], name="auth_usuari_empresa_cbfed6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["email"], name="auth_usuari_email_e53cef_idx"),
        ),
    ]
