# Generated by Django 4.2.9 on 2026-04-09 02:53

from django.db import migrations, models


NOMBRE_TO_SLUG = {
    'Administrador':    'admin',
    'Vendedor':         'vendedor',
    'Almacenista':      'almacenista',
    'Contador':         'contador',
    'Recursos Humanos': 'rrhh',
    'Gerente':          'gerente',
}


def populate_slug(apps, schema_editor):
    Rol = apps.get_model('auth_module', 'Rol')
    for rol in Rol.objects.filter(slug=''):
        slug = NOMBRE_TO_SLUG.get(rol.nombre, rol.nombre.lower().replace(' ', '_'))
        Rol.objects.filter(pk=rol.pk).update(slug=slug)


class Migration(migrations.Migration):
    dependencies = [
        ("auth_module", "0003_usuariosucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="slug",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="usuariosucursal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RunPython(populate_slug, migrations.RunPython.noop),
    ]
