# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ventas_recibidas", models.IntegerField(default=0)),
                ("ventas_ok", models.IntegerField(default=0)),
                ("ventas_conflicto", models.IntegerField(default=0)),
                ("ventas_duplicadas", models.IntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ok", "Sincronizado"),
                            ("conflicto", "Con conflictos"),
                            ("error", "Error"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("detalle", models.JSONField(default=dict)),
                ("dispositivo_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="core.empresa",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="core.sucursal",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sync_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "created_at"],
                        name="sync_logs_empresa_f3d7e2_idx",
                    )
                ],
            },
        ),
    ]
