# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("usuario_email", models.CharField(blank=True, max_length=255)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("venta.creada", "Venta creada"),
                            ("venta.cancelada", "Venta cancelada"),
                            ("venta.pagada", "Venta pagada"),
                            ("devolucion.creada", "Devolución creada"),
                            ("compra.creada", "Compra creada"),
                            ("compra.recibida", "Compra recibida"),
                            ("compra.cancelada", "Compra cancelada"),
                            ("stock.bajo", "Stock bajo mínimo"),
                            ("movimiento.creado", "Movimiento de inventario"),
                            ("cuenta_cobrar.creada", "CxC creada"),
                            ("cuenta_cobrar.pagada", "CxC pagada"),
                            ("cuenta_pagar.creada", "CxP creada"),
                            ("cuenta_pagar.pagada", "CxP pagada"),
                            ("pago.registrado", "Pago registrado"),
                            ("usuario.creado", "Usuario creado"),
                            ("usuario.login", "Inicio de sesión"),
                            ("usuario.logout", "Cierre de sesión"),
                            ("usuario.bloqueado", "Usuario bloqueado"),
                            ("colaborador.creado", "Colaborador creado"),
                            ("asistencia.registrada", "Asistencia registrada"),
                            ("sistema.error_critico", "Error crítico del sistema"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("tabla", models.CharField(blank=True, max_length=100)),
                ("id_registro", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("datos_anteriores", models.JSONField(blank=True, null=True)),
                ("datos_nuevos", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "db_table": "Logs_Auditoria",
                "ordering": ["-created_at"],
            },
        ),
    ]
