# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logauditoria",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs_auditoria",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["empresa", "accion", "created_at"],
                name="Logs_Audito_empresa_04f63c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["empresa", "tabla", "id_registro"],
                name="Logs_Audito_empresa_823c20_idx",
            ),
        ),
    ]
