# Generated by Django 4.2.9 on 2026-07-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("venta.creada", "Venta creada"),
                    ("venta.cancelada", "Venta cancelada"),
                    ("venta.pagada", "Venta pagada"),
                    ("devolucion.creada", "Devolución creada"),
                    ("compra.creada", "Compra creada"),
                    ("compra.recibida", "Compra recibida"),
                    ("compra.cancelada", "Compra cancelada"),
                    ("stock.bajo", "Stock bajo mínimo"),
                    ("movimiento.creado", "Movimiento de inventario"),
                    ("producto.creado", "Producto creado"),
                    ("producto.actualizado", "Producto actualizado"),
                    ("cuenta_cobrar.creada", "CxC creada"),
                    ("cuenta_cobrar.pagada", "CxC pagada"),
                    ("cuenta_cobrar.cancelada", "CxC cancelada"),
                    ("cuenta_cobrar.vencida", "CxC vencida"),
                    ("cuenta_pagar.creada", "CxP creada"),
                    ("cuenta_pagar.pagada", "CxP pagada"),
                    ("cuenta_pagar.cancelada", "CxP cancelada"),
                    ("pago.registrado", "Pago registrado"),
                    ("gasto.registrado", "Gasto registrado"),
                    ("usuario.creado", "Usuario creado"),
                    ("usuario.login", "Inicio de sesión"),
                    ("usuario.logout", "Cierre de sesión"),
                    ("usuario.bloqueado", "Usuario bloqueado"),
                    ("colaborador.creado", "Colaborador creado"),
                    ("asistencia.registrada", "Asistencia registrada"),
                    ("registro.creado", "Registro creado"),
                    ("registro.actualizado", "Registro actualizado"),
                    ("registro.eliminado", "Registro eliminado"),
                    ("sistema.error_critico", "Error crítico del sistema"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
