# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=20)),
                (
                    "tipo_persona",
                    models.CharField(
                        choices=[("fisica", "Física"), ("moral", "Moral")],
                        default="moral",
                        max_length=10,
                    ),
                ),
                ("nombre_comercial", models.CharField(max_length=200)),
                ("razon_social", models.CharField(blank=True, max_length=255)),
                ("rfc", models.CharField(blank=True, max_length=13)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("sitio_web", models.CharField(blank=True, max_length=255)),
                ("contacto_principal", models.CharField(blank=True, max_length=150)),
                ("calle", models.CharField(blank=True, max_length=200)),
                ("numero_exterior", models.CharField(blank=True, max_length=20)),
                ("numero_interior", models.CharField(blank=True, max_length=20)),
                ("colonia", models.CharField(blank=True, max_length=100)),
                ("codigo_postal", models.CharField(blank=True, max_length=10)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=100)),
                ("pais", models.CharField(default="México", max_length=100)),
                ("dias_credito", models.IntegerField(default=0)),
                (
                    "descuento_pronto_pago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("dias_pronto_pago", models.IntegerField(default=0)),
                (
                    "tipo_proveedor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("materia_prima", "Materia Prima"),
                            ("servicios", "Servicios"),
                            ("equipos", "Equipos"),
                            ("consumibles", "Consumibles"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("notas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "terceros_proveedores",
                "indexes": [
                    models.Index(
                        fields=["empresa", "activo"],
                        name="terceros_pr_empresa_ea14f3_idx",
                    ),
                    models.Index(
                        fields=["empresa", "nombre_comercial"],
                        name="terceros_pr_empresa_9efa1a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=20)),
                (
                    "tipo_persona",
                    models.CharField(
                        choices=[("fisica", "Física"), ("moral", "Moral")],
                        default="fisica",
                        max_length=10,
                    ),
                ),
                ("nombre_comercial", models.CharField(max_length=200)),
                ("razon_social", models.CharField(blank=True, max_length=255)),
                ("rfc", models.CharField(blank=True, max_length=13)),
                ("regimen_fiscal", models.CharField(blank=True, max_length=10)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("sitio_web", models.CharField(blank=True, max_length=255)),
                ("calle", models.CharField(blank=True, max_length=200)),
                ("numero_exterior", models.CharField(blank=True, max_length=20)),
                ("numero_interior", models.CharField(blank=True, max_length=20)),
                ("colonia", models.CharField(blank=True, max_length=100)),
                ("codigo_postal", models.CharField(blank=True, max_length=10)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=100)),
                ("pais", models.CharField(default="México", max_length=100)),
                (
                    "limite_credito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("dias_credito", models.IntegerField(default=0)),
                (
                    "credito_disponible",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minorista", "Minorista"),
                            ("mayorista", "Mayorista"),
                            ("distribuidor", "Distribuidor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "descuento_predeterminado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("activo", models.BooleanField(default=True)),
                ("notas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "terceros_clientes",
                "indexes": [
                    models.Index(
                        fields=["empresa", "activo"],
                        name="terceros_cl_empresa_547fae_idx",
                    ),
                    models.Index(
                        fields=["empresa", "nombre_comercial"],
                        name="terceros_cl_empresa_9f2998_idx",
                    ),
                ],
            },
        ),
    ]
