# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("sales", "0001_initial"),
        ("purchases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("terceros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                ("id_cuenta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("banco", models.CharField(blank=True, default="", max_length=100)),
                (
                    "numero_cuenta",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("clabe", models.CharField(blank=True, default="", max_length=18)),
                (
                    "tipo_cuenta",
                    models.CharField(
                        choices=[
                            ("cheques", "Cheques"),
                            ("ahorro", "Ahorro"),
                            ("inversion", "Inversión"),
                            ("caja", "Caja"),
                        ],
                        default="cheques",
                        max_length=20,
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("MXN", "Peso Mexicano"),
                            ("USD", "Dólar Americano"),
                            ("EUR", "Euro"),
                        ],
                        default="MXN",
                        max_length=3,
                    ),
                ),
                (
                    "saldo_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("es_principal", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuentas_bancarias_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_bancarias",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "cuentas_bancarias",
                "ordering": ["-es_principal", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CuentaPorCobrar",
            fields=[
                ("id_cxc", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("folio", models.CharField(max_length=50, unique=True)),
                (
                    "monto_original",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fecha_emision", models.DateField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagada_parcial", "Pagada Parcial"),
                            ("pagada", "Pagada"),
                            ("vencida", "Vencida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuentas_por_cobrar",
                        to="terceros.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cxc_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_por_cobrar",
                        to="core.empresa",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuenta_por_cobrar",
                        to="sales.venta",
                    ),
                ),
            ],
            options={
                "db_table": "cuentas_por_cobrar",
                "ordering": ["fecha_vencimiento", "-id_cxc"],
            },
        ),
        migrations.CreateModel(
            name="CuentaPorPagar",
            fields=[
                ("id_cxp", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("folio", models.CharField(max_length=50, unique=True)),
                (
                    "monto_original",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fecha_emision", models.DateField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagada_parcial", "Pagada Parcial"),
                            ("pagada", "Pagada"),
                            ("vencida", "Vencida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compra",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuenta_por_pagar",
                        to="purchases.compra",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cxp_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_por_pagar",
                        to="core.empresa",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuentas_por_pagar",
                        to="terceros.proveedor",
                    ),
                ),
            ],
            options={
                "db_table": "cuentas_por_pagar",
                "ordering": ["fecha_vencimiento", "-id_cxp"],
            },
        ),
        migrations.CreateModel(
            name="PagoProveedor",
            fields=[
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("folio", models.CharField(max_length=50, unique=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta_debito", "Tarjeta de Débito"),
                            ("tarjeta_credito", "Tarjeta de Crédito"),
                            ("transferencia", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_pago", models.DateField()),
                (
                    "referencia",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_proveedores_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuenta_bancaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_proveedores",
                        to="finance.cuentabancaria",
                    ),
                ),
                (
                    "cxp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="finance.cuentaporpagar",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_proveedores",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "pagos_proveedores",
                "ordering": ["-fecha_pago", "-id_pago"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "fecha_pago"],
                        name="pagos_prove_empresa_1448d7_idx",
                    ),
                    models.Index(fields=["cxp"], name="pagos_prove_cxp_id_d19abc_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PagoCliente",
            fields=[
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("folio", models.CharField(max_length=50, unique=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta_debito", "Tarjeta de Débito"),
                            ("tarjeta_credito", "Tarjeta de Crédito"),
                            ("transferencia", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_pago", models.DateField()),
                (
                    "referencia",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_clientes_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuenta_bancaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_clientes",
                        to="finance.cuentabancaria",
                    ),
                ),
                (
                    "cxc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="finance.cuentaporcobrar",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_clientes",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "pagos_clientes",
                "ordering": ["-fecha_pago", "-id_pago"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "fecha_pago"],
                        name="pagos_clien_empresa_496556_idx",
                    ),
                    models.Index(fields=["cxc"], name="pagos_clien_cxc_id_c455ee_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                ("id_gasto", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("folio", models.CharField(max_length=50, unique=True)),
                ("concepto", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("renta", "Renta"),
                            ("servicios", "Servicios"),
                            ("nomina", "Nómina"),
                            ("mantenimiento", "Mantenimiento"),
                            ("marketing", "Marketing"),
                            ("transporte", "Transporte"),
                            ("impuestos", "Impuestos"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "impuesto_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta_debito", "Tarjeta de Débito"),
                            ("tarjeta_credito", "Tarjeta de Crédito"),
                            ("transferencia", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_gasto", models.DateField()),
                (
                    "referencia",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("comprobante_url", models.URLField(blank=True, default="")),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuenta_bancaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos",
                        to="finance.cuentabancaria",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gastos",
                        to="core.empresa",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos",
                        to="core.sucursal",
                    ),
                ),
            ],
            options={
                "db_table": "gastos",
                "ordering": ["-fecha_gasto", "-id_gasto"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "fecha_gasto"],
                        name="gastos_empresa_87c88a_idx",
                    ),
                    models.Index(
                        fields=["categoria"], name="gastos_categor_453330_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cuentaporpagar",
            index=models.Index(
                fields=["empresa", "estado"], name="cuentas_por_empresa_356a30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuentaporpagar",
            index=models.Index(
                fields=["proveedor"], name="cuentas_por_proveed_753b13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuentaporpagar",
            index=models.Index(
                fields=["fecha_vencimiento"], name="cuentas_por_fecha_v_10e65a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuentaporcobrar",
            index=models.Index(
                fields=["empresa", "estado"], name="cuentas_por_empresa_b45ec2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuentaporcobrar",
            index=models.Index(
                fields=["cliente"], name="cuentas_por_cliente_0665c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuentaporcobrar",
            index=models.Index(
                fields=["fecha_vencimiento"], name="cuentas_por_fecha_v_f9efc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuentabancaria",
            index=models.Index(
                fields=["empresa", "activo"], name="cuentas_ban_empresa_e6681c_idx"
            ),
        ),
    ]
