# Generated by Django 4.2.9 on 2026-06-19 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("terceros", "0002_cliente_sat_fields"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentaporpagar",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cuentas_por_pagar",
                to="terceros.proveedor",
            ),
        ),
    ]
