"""
Plantillas de categorías por giro de negocio.
Cada entrada es una lista de (nombre_categoria, [subcategorias]).
"""

GIRO_CATEGORIAS: dict[str, list[tuple[str, list[str]]]] = {
    'abarrotes': [
        ('Lácteos y Huevo',        ['Leche', 'Quesos', 'Yogurt', 'Huevo']),
        ('Bebidas',                ['Refrescos', 'Agua', 'Jugos', 'Bebidas Energéticas']),
        ('Botanas y Snacks',       ['Papas', 'Cacahuates', 'Galletas', 'Dulces']),
        ('Carnes y Embutidos',     ['Jamón', 'Chorizo', 'Salchichas', 'Mortadela']),
        ('Frutas y Verduras',      []),
        ('Granos y Cereales',      ['Arroz', 'Frijol', 'Lentejas', 'Avena']),
        ('Panadería',              ['Pan Blanco', 'Pan Dulce', 'Tortillas']),
        ('Limpieza del Hogar',     ['Detergente', 'Cloro', 'Suavizante', 'Desengrasante']),
        ('Higiene Personal',       ['Jabón', 'Shampoo', 'Pasta Dental', 'Desodorante']),
        ('Enlatados y Conservas',  ['Atún', 'Sardinas', 'Chiles', 'Salsas']),
    ],
    'zapateria': [
        ('Caballero',    ['Tenis', 'Zapato Formal', 'Botas', 'Huaraches']),
        ('Dama',         ['Tacones', 'Flats', 'Botas Dama', 'Sandalias']),
        ('Infantil',     ['Niño', 'Niña', 'Bebé']),
        ('Deportivo',    ['Running', 'Fútbol', 'Basketball', 'Training']),
        ('Accesorios',   ['Calcetines', 'Cinturones', 'Agujetas', 'Insoles']),
    ],
    'licoreria': [
        ('Cervezas',           ['Nacional', 'Importada', 'Artesanal', 'Sin Alcohol']),
        ('Vinos',              ['Tinto', 'Blanco', 'Rosado', 'Espumoso']),
        ('Tequila y Mezcal',   ['Blanco', 'Reposado', 'Añejo', 'Mezcal']),
        ('Destilados',         ['Whisky', 'Ron', 'Vodka', 'Ginebra', 'Brandy']),
        ('Cocteles Listos',    []),
        ('Refrescos y Agua',   []),
        ('Botanas',            []),
    ],
    'restaurante': [
        ('Desayunos',     ['Huevos', 'Hotcakes', 'Chilaquiles', 'Jugos']),
        ('Entradas',      ['Sopas', 'Ensaladas', 'Antojitos']),
        ('Platos Fuertes',['Carnes', 'Aves', 'Mariscos', 'Vegetariano']),
        ('Bebidas',       ['Refrescos', 'Aguas Frescas', 'Café', 'Bebidas Alcohólicas']),
        ('Postres',       ['Pasteles', 'Flanes', 'Helados', 'Frutas']),
        ('Para Llevar',   []),
    ],
    'farmacia': [
        ('Medicamentos',         ['Analgésicos', 'Antibióticos', 'Antigripales', 'Antiácidos']),
        ('Vitaminas y Suplementos', ['Multivitamínicos', 'Omega 3', 'Proteínas', 'Probióticos']),
        ('Higiene Personal',     ['Jabón', 'Shampoo', 'Cuidado Dental']),
        ('Cuidado del Bebé',     ['Pañales', 'Leche de Fórmula', 'Cremas', 'Accesorios']),
        ('Equipos Médicos',      ['Tensiómetros', 'Glucómetros', 'Termómetros']),
        ('Primeros Auxilios',    ['Vendajes', 'Antisépticos', 'Apósitos']),
    ],
    'ferreteria': [
        ('Herramientas Manuales',    ['Martillos', 'Desarmadores', 'Llaves', 'Pinzas']),
        ('Herramientas Eléctricas',  ['Taladros', 'Esmeriles', 'Sierras', 'Pulidoras']),
        ('Plomería',                 ['Tuberías', 'Llaves de Paso', 'Conexiones', 'Bombas']),
        ('Electricidad',             ['Cable', 'Contactos', 'Focos', 'Clavijas']),
        ('Pinturas y Acabados',      ['Pintura Vinílica', 'Pintura Aceite', 'Brochas', 'Rodillos']),
        ('Fijaciones',               ['Tornillos', 'Clavos', 'Anclas', 'Pegamentos']),
        ('Materiales de Construcción', ['Cemento', 'Varilla', 'Grava', 'Malla']),
    ],
    'ropa': [
        ('Dama',            ['Blusas', 'Pantalones', 'Vestidos', 'Faldas', 'Ropa Interior']),
        ('Caballero',       ['Camisas', 'Pantalones', 'Trajes', 'Ropa Interior']),
        ('Niños',           ['Bebé 0-2', 'Niño 3-7', 'Juvenil 8-14']),
        ('Ropa Deportiva',  ['Pants', 'Playeras', 'Shorts', 'Leggings']),
        ('Accesorios',      ['Cinturones', 'Bolsas', 'Gorras', 'Bufandas']),
        ('Temporada',       ['Invierno', 'Verano', 'Liquidación']),
    ],
    'panaderia': [
        ('Pan Dulce',   ['Conchas', 'Cuernos', 'Polvorones', 'Empanadas']),
        ('Pan Salado',  ['Telera', 'Bolillo', 'Baguette', 'Integral']),
        ('Pasteles',    ['Cumpleaños', 'Bodas', 'Individuales', 'Cheesecake']),
        ('Galletas',    ['Mantequilla', 'Decoradas', 'Saladas']),
        ('Tortillas',   ['Harina', 'Maíz']),
        ('Bebidas',     ['Café', 'Leche', 'Atole', 'Champurrado']),
    ],
    'electronica': [
        ('Celulares y Smartphones', ['iPhone', 'Samsung', 'Xiaomi', 'Otros']),
        ('Accesorios Celular',       ['Fundas', 'Cargadores', 'Audífonos', 'Cables']),
        ('Computadoras',             ['Laptops', 'Desktops', 'Tablets']),
        ('Audio y Video',            ['Bocinas', 'Audífonos', 'Smart TV', 'Proyectores']),
        ('Consolas y Videojuegos',   ['PlayStation', 'Xbox', 'Nintendo', 'Juegos']),
        ('Reparación y Servicio',    ['Pantallas', 'Baterías', 'Mano de Obra']),
        ('Cables y Adaptadores',     []),
    ],
    'papeleria': [
        ('Útiles Escolares',    ['Cuadernos', 'Libretas', 'Lápices', 'Bolígrafos', 'Colores']),
        ('Oficina',             ['Archiveros', 'Carpetas', 'Post-it', 'Clips', 'Grapadoras']),
        ('Arte y Manualidades', ['Pinturas', 'Pinceles', 'Lienzos', 'Cartulinas']),
        ('Impresión',           ['Tóner', 'Tintas', 'Papel Bond', 'Papel Fotográfico']),
        ('Libros',              ['Escolares', 'Técnicos', 'Literatura', 'Infantiles']),
        ('Tecnología',          ['USB', 'Cables', 'Ratones', 'Teclados']),
    ],
    'veterinaria': [
        ('Perros',        ['Alimento Cachorro', 'Alimento Adulto', 'Snacks', 'Accesorios']),
        ('Gatos',         ['Alimento Gato', 'Areneros', 'Juguetes', 'Accesorios']),
        ('Medicamentos',  ['Antiparasitarios', 'Vitaminas', 'Antibióticos']),
        ('Higiene',       ['Shampoos', 'Cepillos', 'Aromas']),
        ('Aves y Peces',  ['Alimento Aves', 'Alimento Peces', 'Acuarios']),
        ('Servicios',     ['Consulta', 'Vacunas', 'Estética', 'Cirugía']),
    ],
    'estetica': [
        ('Corte y Peinado',   ['Corte Dama', 'Corte Caballero', 'Peinado', 'Cepillado']),
        ('Color y Tintes',    ['Tinte Completo', 'Mechas', 'Balayage', 'Decoloración']),
        ('Tratamientos',      ['Keratina', 'Hidratación', 'Botox Capilar']),
        ('Uñas',              ['Manicure', 'Pedicure', 'Acrílicas', 'Gel']),
        ('Maquillaje',        ['Social', 'Artístico', 'Micropigmentación']),
        ('Productos de Venta', ['Shampoos', 'Acondicionadores', 'Tintes', 'Accesorios']),
    ],
    'gimnasio': [
        ('Membresías',          ['Mensual', 'Trimestral', 'Semestral', 'Anual']),
        ('Clases',              ['Spinning', 'Yoga', 'Zumba', 'Box', 'Pilates']),
        ('Suplementos',         ['Proteínas', 'Pre-Entreno', 'Creatina', 'BCAA', 'Vitaminas']),
        ('Ropa Deportiva',      ['Dama', 'Caballero', 'Calzado']),
        ('Accesorios',          ['Guantes', 'Fajas', 'Cuerdas', 'Bandas']),
    ],
    'carniceria': [
        ('Res',                 ['Arrachera', 'Filete', 'Costilla', 'Molida', 'Carne para Asar']),
        ('Cerdo',               ['Chuleta', 'Costilla', 'Lomo', 'Carnitas', 'Chicharrón']),
        ('Pollo',               ['Entero', 'Pechuga', 'Pierna y Muslo', 'Alas', 'Molida']),
        ('Mariscos',            ['Camarón', 'Filete de Pescado', 'Pulpo', 'Calamar']),
        ('Embutidos',           ['Jamón', 'Salchicha', 'Chorizo', 'Salami', 'Tocino']),
        ('Barbacoa y Birria',   []),
    ],
    'flores': [
        ('Arreglos Florales',   ['Ramos', 'Centros de Mesa', 'Coronas', 'Caja de Flores']),
        ('Flores Sueltas',      ['Rosas', 'Girasoles', 'Lilis', 'Margaritas', 'Orquídeas']),
        ('Plantas de Interior', ['Suculentas', 'Cactus', 'Helechos', 'Pothos']),
        ('Plantas de Exterior', ['Arbustos', 'Árboles', 'Pasto', 'Flores de Jardín']),
        ('Macetas y Accesorios',['Macetas', 'Tierra', 'Abono', 'Macetas Decorativas']),
        ('Regalos',             ['Globos', 'Chocolates', 'Peluches', 'Tarjetas']),
    ],
    'joyeria': [
        ('Anillos',             ['Compromiso', 'Bodas', 'Moda', 'Sello']),
        ('Collares y Cadenas',  ['Oro', 'Plata', 'Acero', 'Fantasía']),
        ('Pulseras',            ['Oro', 'Plata', 'Hilo', 'Acero']),
        ('Aretes',              ['Oro', 'Plata', 'Fantasía', 'Perlas']),
        ('Relojes',             ['Dama', 'Caballero', 'Unisex']),
        ('Bisutería',           []),
        ('Reparaciones',        ['Soldadura', 'Limpieza', 'Engaste']),
    ],
    'jugueteria': [
        ('Bebé 0-2 años',       ['Sonajeros', 'Móviles', 'Andaderas']),
        ('Preescolar 3-5',      ['Figuras', 'Puzzles', 'Educativos']),
        ('Niños 6-12',          ['Figuras de Acción', 'Muñecas', 'LEGO', 'Radio Control']),
        ('Juegos de Mesa',      ['Estrategia', 'Clásicos', 'Cartas']),
        ('Deportes',            ['Pelotas', 'Bicis', 'Patines', 'Albercas']),
        ('Videojuegos',         ['Consolas', 'Juegos', 'Accesorios']),
        ('Disfraces',           []),
    ],
    'muebleria': [
        ('Sala',       ['Sillones', 'Sofás', 'Mesas de Centro', 'Estantes']),
        ('Comedor',    ['Mesas', 'Sillas', 'Barras', 'Vitrinas']),
        ('Recámara',   ['Camas', 'Colchones', 'Guardarropas', 'Burós']),
        ('Cocina',     ['Alacenas', 'Mesas de Cocina', 'Microondas', 'Refrigeradores']),
        ('Baño',       ['Muebles de Baño', 'Espejos', 'Accesorios']),
        ('Oficina',    ['Escritorios', 'Sillas de Oficina', 'Libreros']),
        ('Decoración', ['Cuadros', 'Lámparas', 'Tapetes', 'Cojines']),
    ],
    'otro': [],
}
