# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=50)),
                ("abreviatura", models.CharField(blank=True, max_length=10)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pieza", "Pieza"),
                            ("peso", "Peso"),
                            ("volumen", "Volumen"),
                            ("longitud", "Longitud"),
                            ("tiempo", "Tiempo"),
                            ("area", "Área"),
                            ("otro", "Otro"),
                        ],
                        default="pieza",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_medida",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "db_table": "catalogs_unidades_medida",
                "indexes": [
                    models.Index(
                        fields=["empresa", "activo"],
                        name="catalogs_un_empresa_f2b870_idx",
                    )
                ],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="Impuesto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=50)),
                ("tasa", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("IVA", "IVA"),
                            ("IEPS", "IEPS"),
                            ("ISR", "ISR"),
                            ("otro", "Otro"),
                        ],
                        default="IVA",
                        max_length=20,
                    ),
                ),
                ("es_retencion", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impuestos",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
                "db_table": "catalogs_impuestos",
                "indexes": [
                    models.Index(
                        fields=["empresa", "activo"],
                        name="catalogs_im_empresa_be25af_idx",
                    )
                ],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=20)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="core.empresa",
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategorias",
                        to="catalogs.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "catalogs_categorias",
                "indexes": [
                    models.Index(
                        fields=["empresa", "activo"],
                        name="catalogs_ca_empresa_f77316_idx",
                    )
                ],
                "unique_together": {("empresa", "codigo")},
            },
        ),
    ]
