# Generated by Django 4.2.9 on 2026-03-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("terceros", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocion",
            fields=[
                ("id_promocion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("codigo", models.CharField(blank=True, max_length=50, null=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "tipo_descuento",
                    models.CharField(
                        choices=[
                            ("porcentaje", "Porcentaje"),
                            ("monto_fijo", "Monto Fijo"),
                        ],
                        default="porcentaje",
                        max_length=20,
                    ),
                ),
                ("descuento", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "aplica_a",
                    models.CharField(
                        choices=[
                            ("total", "Total de la venta"),
                            ("producto", "Producto específico"),
                            ("categoria", "Categoría"),
                        ],
                        default="total",
                        max_length=20,
                    ),
                ),
                ("ids_aplicables", models.JSONField(blank=True, default=list)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "monto_minimo_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("cantidad_maxima_uso", models.IntegerField(blank=True, null=True)),
                ("cantidad_usado", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promociones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promociones",
                        to="core.empresa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promociones_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promociones",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id_venta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("folio", models.CharField(max_length=50, unique=True)),
                ("fecha_venta", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("cancelado", "Cancelado"),
                            ("pagado", "Pagado"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta_debito", "Tarjeta de Débito"),
                            ("tarjeta_credito", "Tarjeta de Crédito"),
                            ("transferencia", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("credito", "Crédito"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("requiere_factura", models.BooleanField(default=False)),
                ("facturado", models.BooleanField(default=False)),
                ("uuid_factura", models.UUIDField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "offline_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="online",
                        max_length=10,
                    ),
                ),
                ("sincronizado_at", models.DateTimeField(blank=True, null=True)),
                ("conflicto", models.BooleanField(default=False)),
                ("conflicto_detalle", models.TextField(blank=True, default="")),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas",
                        to="terceros.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to="core.empresa",
                    ),
                ),
                (
                    "promocion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas",
                        to="sales.promocion",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="core.sucursal",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ventas",
                "ordering": ["-fecha_venta"],
            },
        ),
        migrations.CreateModel(
            name="Devolucion",
            fields=[
                ("id_devolucion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("folio", models.CharField(max_length=50, unique=True)),
                ("fecha_devolucion", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.CharField(max_length=255)),
                ("observaciones", models.TextField(blank=True, default="")),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "metodo_reembolso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta_debito", "Tarjeta de Débito"),
                            ("tarjeta_credito", "Tarjeta de Crédito"),
                            ("transferencia", "Transferencia"),
                            ("nota_credito", "Nota de Crédito"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("reembolsado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoluciones",
                        to="core.empresa",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones",
                        to="core.sucursal",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones",
                        to="sales.venta",
                    ),
                ),
            ],
            options={
                "db_table": "devoluciones",
                "ordering": ["-fecha_devolucion"],
            },
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                ("id_detalle", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "impuesto_tasa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "impuesto_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "costo_unitario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_venta",
                        to="inventory.producto",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_venta",
                        to="inventory.varianteproducto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="sales.venta",
                    ),
                ),
            ],
            options={
                "db_table": "detalle_ventas",
                "ordering": ["id_detalle"],
            },
        ),
        migrations.CreateModel(
            name="DetalleDevolucion",
            fields=[
                ("id_detalle", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "impuesto_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "detalle_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones",
                        to="sales.detalleventa",
                    ),
                ),
                (
                    "devolucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="sales.devolucion",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_devolucion",
                        to="inventory.producto",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_devolucion",
                        to="inventory.varianteproducto",
                    ),
                ),
            ],
            options={
                "db_table": "detalle_devoluciones",
                "ordering": ["id_detalle"],
            },
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["empresa", "fecha_venta"], name="ventas_empresa_399d30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["sucursal", "fecha_venta"], name="ventas_sucursa_d3863d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(fields=["cliente"], name="ventas_cliente_b73e43_idx"),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(fields=["estado"], name="ventas_estado_505824_idx"),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(fields=["folio"], name="ventas_folio_69d9d1_idx"),
        ),
        migrations.AddIndex(
            model_name="promocion",
            index=models.Index(
                fields=["empresa", "activo"], name="promociones_empresa_82084e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promocion",
            index=models.Index(
                fields=["fecha_inicio", "fecha_fin"],
                name="promociones_fecha_i_a974ad_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="promocion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("codigo__isnull", False)),
                fields=("empresa", "codigo"),
                name="unique_promocion_codigo_empresa",
            ),
        ),
        migrations.AddIndex(
            model_name="devolucion",
            index=models.Index(
                fields=["empresa", "fecha_devolucion"],
                name="devolucione_empresa_0230ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devolucion",
            index=models.Index(fields=["venta"], name="devolucione_venta_i_7db3e9_idx"),
        ),
    ]
