# Generated by Django 4.2.9 on 2026-03-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="venta",
            name="ventas_folio_69d9d1_idx",
        ),
        migrations.AlterField(
            model_name="venta",
            name="folio",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="venta",
            unique_together={("empresa", "folio")},
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["empresa", "folio"], name="ventas_empresa_59b8f6_idx"
            ),
        ),
    ]
