# Generated by Django 4.2.9 on 2026-04-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_folio_unique_per_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="notas",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Nota libre por línea de venta. Ej: "sin sal", "mitad cocido".',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="cambio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cambio devuelto al cliente (monto_recibido - total).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="monto_recibido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto entregado por el cliente. Solo aplica para pagos en efectivo.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
